// Generated by IcedCoffeeScript 108.0.11
(function() {
  var http, server;

  http = require('http');

  server = http.createServer(function(req, res) {
    req.setEncoding('utf8');
    req.on('data', function(chunk) {
      return res.write(chunk);
    });
    return req.on('end', function() {
      res.write("End stream");
      return res.end();
    });
  });

  server.listen(39393);

}).call(this);
