// Generated by IcedCoffeeScript 108.0.11
(function() {
  var b64, enc, http, server, stream_data;

  enc = require('./encoding');

  http = require('http');

  b64 = enc.b64.encoding;

  stream_data = function(src, dst) {
    return src.on('data', function(chunk) {
      return dst.write(b64.decode(new Buffer(chunk, 'utf-8')));
    });
  };

  server = http.createServer(function(req, res) {
    stream_data(req, res);
    return req.on('end', function() {
      return res.end();
    });
  });

  server.listen(39393);

}).call(this);
